### DISCUSSION TITLE
ovpn-admin

### DISCUSSION THREAD

**Discussion by crubik** [xtrime-ru/antizapret-vpn-docker#117] [Q&A] [answered]
Возможно ли приделать ovpn-admin в вашу систему?
https://habr.com/ru/companies/flant/articles/543986/

**Comment by xtrime-ru** [comment, marked as answer]
https://github.com/xtrime-ru/antizapret-vpn-docker/tree/openvp-move-to-container - тут сделано (но доки не обновлены). 

Но у меня почему то openvpn из нового контейнера блочилась, а старая ветка работала. Еще не успел разобраться в чем причина: в настройках openvpn или просто приколы РКН с выборочной блокировкой.

Вот пример docker-compose.override.yml для тестов: 

```
services:
  antizapret-vpn:
    env_file: !reset []
    environment:
      - ADGUARDHOME_PASSWORD=BgENn7SMCdmk6Ka4tq9xJ5
  openvpn:
    environment:
      - OPENVPN_ADMIN_PASSWORD=BgENn7SMCdmk6Ka4tq9xJ5
    env_file: !reset []
    extends:
      file: docker-compose.openvpn.yml
      service: openvpn
  wireguard-amnezia:
    environment:
      - WIREGUARD_PASSWORD=BgENn7SMCdmk6Ka4tq9xJ5
    env_file: !reset []
    extends:
      file: docker-compose.wireguard-amnezia.yml
      service: wireguard-amnezia
 ```
