### DISCUSSION TITLE
Обновления до v4

### DISCUSSION THREAD

**Discussion by Murakumo-JP** [xtrime-ru/antizapret-vpn-docker#136] [Q&A] [answered]
Здраствуйте увидел что вышла крупное обновления и всё поменялось, теперь сижу и задоюсь вопросом а что мне стоит сделать чтоб успешно обновится до v4 и нечего не сломать.
Имею сейчас такой вот конфиг docker-compose.override.yml
```yaml
services:
  antizapret-vpn:
    environment:
      - DNS=adguardhome
      - ADGUARD=1
      - OPENVPN_OPTIMIZATIONS=1
      - OPENVPN_TLS_CRYPT=1
      - OPENVPN_PORT=6841
      - SKIP_UPDATE_FROM_ZAPRET=true
      - UPDATE_TIMER=360d
    ports:
      - "6841:1194/tcp"
      - "6841:1194/udp"
    depends_on:
      - adguardhome
  adguardhome:
    extends:
      file: docker-compose.adguard.yml
      service: adguardhome
      container_name: adguardhome
    ports:
      - "6845:80/tcp"
  amnezia-wg-easy:
    environment:
      - WG_ALLOWED_IPS=0.0.0.0/0
      - FORCE_FORWARD_DNS=true
      - LANGUAGE=ru
      - PORT=6843
      - WG_PORT=443
    ports:
      - "6843:6843/tcp"
      - "443:443/udp"
    extends:
      file: docker-compose.wireguard-amnezia.yml
      service: amnezia-wg-easy
```
Мне нужно сохранить работоспособность AmneziaWG, OpenVPN ну и Adguard я видел новую инструкцию там нет OpenVPN в yam файле конфига как тут по этому задаюсь вопросом как теперь всё это сделать чтоб работала как и раньше.

**Comment by xtrime-ru** [comment, marked as answer]
Примерно так: 

```yml
services:
  antizapret:
    environment:
      - SKIP_UPDATE_FROM_ZAPRET=true
      - UPDATE_TIMER=360d
      - ADGUARDHOME_PASSWORD=заменить_на_свой_пароль
    ports:
      - "6845:3000/tcp"
  openvpn:
    extends:
      file: docker-compose.openvpn.yml
      service: openvpn
    environment:
      - OBFUSCATE_TYPE=2
    ports:
      - "6841:1194/udp"
  openvpn-ui:
    environment:
      - OPENVPN_ADMIN_PASSWORD=заменить_на_свой_пароль
    extends:
      file: docker-compose.openvpn.yml
      service: openvpn-ui
  wireguard-amnezia:
    environment:
      - WIREGUARD_PASSWORD= заменить_на_свой_пароль
      - WG_ALLOWED_IPS=0.0.0.0/0
      - FORCE_FORWARD_DNS=true
      - LANGUAGE=ru
      - PORT=6843
      - WG_PORT=443
    ports:
      - "6843:6843/tcp"
      - "443:443/udp"
    extends:
      file: docker-compose.wireguard-amnezia.yml
      service: wireguard-amnezia
   ```
