### DISCUSSION TITLE
Ключи из LXC контейнера в v4

### DISCUSSION THREAD

**Discussion by TheSainEyereg** [xtrime-ru/antizapret-vpn-docker#148] [Q&A]
В сентябре прошлого года я [задал вопрос касаемо переноса ключей из LXC контейнера](https://github.com/xtrime-ru/antizapret-vpn-docker/discussions/56) в тогдашнюю v3. Сейчас в README сказано, что перенести конфиги можно только от WG и AWG, т.е. совместимость со старым OpenVPN конфигом потеряна?

Текущий `docker-compose.override.yml `:
```yaml
services:
  antizapret-vpn:
    image: xtrime/antizapret-vpn:latest
    container_name: antizapret-vpn
    hostname: antizapret
    restart: always
    privileged: true
    stop_signal: SIGRTMIN+4
    build: .
    environment:
      - OPENVPN_CBC_CIPHERS=1
      - OPENVPN_OPTIMIZATIONS=1
      - OPENVPN_TLS_CRYPT=0
    ports: !override
      - 443:1194/tcp
      - 443:1194/udp
    dns:
      - 1.1.1.1
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./keys:/etc/openvpn
      - ./config:/root/antizapret/config/custom
    logging:
      driver: json-file
      options:
        max-size: 100k
        max-file: 2
  amnezia-wg-easy:
    extends:
      file: docker-compose.wireguard-amnezia.yml
      service: amnezia-wg-easy
    environment:
      - WG_PORT=8443
      - JC=5
      - JMIN=40
      - JMAX=70
    ports: !override
      - 8443:8443/udp
      - 51821:51821/tcp
```

Также там приходилось комментировать строки в `generate.sh`, его местоположение и структура не поменялась?
