### DISCUSSION TITLE
docker-compose.adguard.yml

### DISCUSSION THREAD

**Discussion by crubik** [xtrime-ru/antizapret-vpn-docker#28] [General]
Здравствуйте.
В связи с тем что я только изучаю эти докеры. Хотелось бы немного инструкции как установить AdGuard "рядом" с сервером антизапрета?

**Comment by xtrime-ru** [comment]
```
docker compose down
docker compose -f docker-compose.adguard.yml up -d
```
Панель adguard будет доступна по адресу ip_сервера:3000

Все настройки уже есть в docker-compose.adguard.yml, ничего делать не надо.

**Reply by crubik** [reply]
понял\принял. спасибо

**Comment by crubik** [comment]
вот еще затык. 
при добавлении pem пути от Lets Enycrypt для сайта AdGuard - он не видит пути к этим pem, хотя они в каталоге присутствуют
![Screenshot_7](https://github.com/user-attachments/assets/9b3dad95-50f0-4c62-a6bd-133f625d0330)

**Reply by xtrime-ru** [reply]
Я к сожалению не знаю что это, так как не пользуюсь adguard. 
Но так как adguard в контейнере, то он не имеет доступа к файловой системе хоста. 

Искючение - смонтированные папки : https://github.com/xtrime-ru/antizapret-vpn-docker/blob/master/docker-compose.adguard.yml#L23

Нужно положить файлы в папку .adguard/workdir или .adguard/confdir и они будут доступны соответственно внутри контейнера по адресам /opt/adguardhome/work или /opt/adguardhome/conf

**Reply by crubik** [reply]
> Нужно положить файлы в папку .adguard/workdir или .adguard/confdir и они будут доступны соответственно внутри контейнера по адресам /opt/adguardhome/work или /opt/adguardhome/conf

помогло, но вот только на 3 месяца хватит такой манипуляции)

**Reply by xtrime-ru** [reply]
Если это сертификат домена, чтобы https работали, то проблема решается контейнером с [caddy](https://caddyserver.com). Он сам будет обновлять сертификаты через letsencrypt. Настроить его как reverse proxy, а в качестве бекенда указать контейнер adguard. Ну и публикацию портов 80 и 443 перенести из adguard в caddy. 

Отличная задача, что бы понять как докер работает :)

Оснвной принцип - единоличная ответственность. Каждый модуль/контейнер должен делать что то одно. caddy - поддержка https, adguard - dns, antizapret - обход блокировок и VPN. 

В последнем случае принцип ломается, и надо выносить из антизапрета openvpn и добавлять поддержку других транспортных протоколов.

**Reply by crubik** [reply]
> Если это сертификат домена, чтобы https работали, то проблема решается контейнером с [caddy](https://caddyserver.com). Он сам будет обновлять сертификаты через letsencrypt. Настроить его как reverse proxy, а в качестве бекенда указать контейнер adguard. Ну и публикацию портов 80 и 443 перенести из adguard в caddy.
> 
> Отличная задача, что бы понять как докер работает :)
> 
> Оснвной принцип - единоличная ответственность. Каждый модуль/контейнер должен делать что то одно. caddy - поддержка https, adguard - dns, antizapret - обход блокировок и VPN.
> 
> В последнем случае принцип ломается, и надо выносить из антизапрета openvpn и добавлять поддержку других транспортных протоколов.

![1670667494122444082](https://github.com/user-attachments/assets/add08187-a290-4dd1-8df7-b5d743f6072b)

**Reply by xtrime-ru** [reply]
```yml
services:
  antizapret-vpn:
    extends:
      file: docker-compose.base.yml
      service: antizapret-vpn
    networks:
      default:
      static-network:
        ipv4_address: 10.5.0.2
    environment:
      - DNS=10.5.0.3
  adguardhome:
    image: adguard/adguardhome
    ports:
#      - 53:53/tcp
#      - 53:53/udp
#      - 784:784/udp
#      - 853:853/tcp
      - 3000:3000/tcp
#      - 80:80/tcp
#      - 443:443/tcp
    volumes:
      - ./.adguard/workdir:/opt/adguardhome/work
      - ./.adguard/confdir:/opt/adguardhome/conf
    restart: unless-stopped
    networks:
      default:
      static-network:
        ipv4_address: 10.5.0.3
  caddy:
    image: caddy:latest
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"
    volumes:
      - $PWD/Caddyfile:/etc/caddy/Caddyfile
      - $PWD/site:/srv
      - caddy_data:/data
      - caddy_config:/config
    networks:
      default:
      static-network:
        ipv4_address: 10.5.0.4
networks:
  static-network:
    driver: bridge
    ipam:
      config:
        - subnet: 10.5.0.0/24
          gateway: 10.5.0.1

volumes:
  caddy_data:
    external: true
  caddy_config:
```

Ну и положить конфиги в папки Caddyfile и site

**Reply by crubik** [reply]
> Ну и положить конфиги в папки Caddyfile и site

- $PWD/Caddyfile:/etc/caddy/Caddyfile
      - $PWD/site:/srv

это пути в контейнере к Caddy?

**Reply by xtrime-ru** [reply]
> это пути в контейнере к Caddy?

до двоеточия путь на хосте, после - в контенере.

https://docs.docker.com/engine/storage/volumes/#:~:text=Volumes%20are%20the%20preferred%20mechanism,are%20completely%20managed%20by%20Docker.

обращаю внимание, что в docker compose теперь три контейнера: antizapret, adguard, caddy

**Reply by crubik** [reply]
> обращаю внимание, что в docker compose теперь три контейнера: antizapret, adguard, caddy

все так и нужно

**Reply by crubik** [reply]
> ```yaml
> services:
>   antizapret-vpn:
>     extends:
>       file: docker-compose.base.yml
>       service: antizapret-vpn
>     networks:
>       default:
>       static-network:
>         ipv4_address: 10.5.0.2
>     environment:
>       - DNS=10.5.0.3
>   adguardhome:
>     image: adguard/adguardhome
>     ports:
> #      - 53:53/tcp
> #      - 53:53/udp
> #      - 784:784/udp
> #      - 853:853/tcp
>       - 3000:3000/tcp
> #      - 80:80/tcp
> #      - 443:443/tcp
>     volumes:
>       - ./.adguard/workdir:/opt/adguardhome/work
>       - ./.adguard/confdir:/opt/adguardhome/conf
>     restart: unless-stopped
>     networks:
>       default:
>       static-network:
>         ipv4_address: 10.5.0.3
>   caddy:
>     image: caddy:latest
>     restart: unless-stopped
>     cap_add:
>       - NET_ADMIN
>     ports:
>       - "80:80"
>       - "443:443"
>       - "443:443/udp"
>     volumes:
>       - $PWD/Caddyfile:/etc/caddy/Caddyfile
>       - $PWD/site:/srv
>       - caddy_data:/data
>       - caddy_config:/config
>     networks:
>       default:
>       static-network:
>         ipv4_address: 10.5.0.4
> networks:
>   static-network:
>     driver: bridge
>     ipam:
>       config:
>         - subnet: 10.5.0.0/24
>           gateway: 10.5.0.1
> 
> volumes:
>   caddy_data:
>     external: true
>   caddy_config:
> ```
> 
> Ну и положить конфиги в папки Caddyfile и site

не запускается Caddy. добавляю код в docker-compose.adguard.yml и выбивает с ошибкой
![Screenshot_4](https://github.com/user-attachments/assets/e1642db1-2b96-4d23-9239-e0368e2b0c7f)

**Reply by xtrime-ru** [reply]
Обрати внимание на последние 4 строки. Я обновлял сообщение.

**Reply by crubik** [reply]
> Обрати внимание на последние 4 строки. Я обновлял сообщение.
не хочет. та же ошибка
![Screenshot_5](https://github.com/user-attachments/assets/b59fb929-059c-4848-b2ce-7fb5d6643d0d)

**Reply by xtrime-ru** [reply]
Возможно нужно сделать docker compose -f docker-compose.adguard.yml down && docker compose -f docker-compose.adguard.yml up -d

Если не поможет то решение должно отыскаться в гугле

**Reply by crubik** [reply]
> Если не поможет то решение должно отыскаться в гугле

без вас снова не получается(
https://hub.docker.com/_/caddy

Читаю мануал и на пункте
![Screenshot_2](https://github.com/user-attachments/assets/32c37345-2bd1-455b-9023-444850b979f3)

ловлю снова ошибки(
![Screenshot_4](https://github.com/user-attachments/assets/74c81605-17fc-400d-b1c4-31f2fc1eb256)

**Reply by xtrime-ru** [reply]
Да забей на эти volume, смонтируй их тоже как папки и пофигу на них :)

**Reply by crubik** [reply]
> Да забей на эти volume, смонтируй их тоже как папки и пофигу на них :)

- caddy_data:/data
- caddy_config:/config

это вот про это?

**Comment by crubik** [comment]
```
  caddy:
    image: caddy:latest
    restart: always
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - ./site:/var/www/html
```
вот так?
