### ISSUE TITLE
Не работает голос в Discord через OpenVPN на роутере Keenetic

### ISSUE THREAD

**Issue by TTATPuOT** [xtrime-ru/antizapret-vpn-docker#144]
Всем привет!
Пользовался сборкой с версии 3, на которой тоже наблюдались некоторые проблемы с доступом #98 . Но тогда удалось каким-то образом починить и дискорд работал без нареканий.

Сейчас, поднимая сервер на 4 версии, столкнулся с похожей проблемой. При входе в голосовой канал происходит долгая загрузка "RTC Connecting", а затем ошибка "No Route" - и всё по кругу до бесконечности. При этом, остальные функции работают: чат, отправка файлов, просмотр каналов и т.д.

VPN подключен к [роутеру Keenetic по инструкции](https://github.com/xtrime-ru/antizapret-vpn-docker/blob/master/docs/guide_Keenetic_RU.md) через OpenVPN. Собственно, настройку роутера с 3 версии не менял, только обновил конфиг на новый. Остальные сервисы, кроме Discord, работают без нареканий.

Дополнительно, пробовал добавить в `/config/antizapret/custom/include-hosts-custom.txt` следующий список, но это ни на что не влияет:

<details>
  <summary>include-hosts-custom.txt</summary>

```
digitalocean.com
1187013846746005515.discordsays.com
cdn.discordapp.com
dis.gd
discord-activities.com
discord.co
discord.com
discord.design
discord.dev
discord.gift
discord.gifts
discord.new
discord.store
discord.tools
discordactivities.com
discordapp.com
discordapp.net
discordcdn.com
discordmerch.com
discordpartygames.com
discordsays.com
discordstatus.com
images-ext-1.discordapp.net
images-ext-2.discordapp.net
media.discordapp.net
status.discord.com
updates.discord.com
discord-attachments-uploads-prd.storage.googleapis.com
curseforge.com
gateway.discord.gg
```

</details>

Docker-compose файл максимально простой:

<details>
  <summary>docker-compose.override.yaml</summary>

```yaml
services:
  antizapret:
    environment:
      - ADGUARDHOME_PASSWORD=secret

  openvpn:
    extends:
      file: docker-compose.openvpn.yml
      service: openvpn
    environment:
      - OBFUSCATE_TYPE=2

  openvpn-ui:
    environment:
      - OPENVPN_ADMIN_PASSWORD=secret
    extends:
      file: docker-compose.openvpn.yml
      service: openvpn-ui

  wireguard-amnezia:
    environment:
      - WIREGUARD_PASSWORD=secret
    extends:
      file: docker-compose.wireguard.yml
      service: wireguard
```

</details>

Логи в antizapret и openvpn контейнерах при попытке подключения к каналу:

```
antizapret-1         | Feb 08 09:41:58 dnsmap[142]: Mapping 10.224.0.32 to 162.159.129.232
antizapret-1         | Feb 08 09:41:58 dnsmap[142]: Mapping 10.224.0.33 to 162.159.130.232
antizapret-1         | Feb 08 09:41:58 dnsmap[142]: Mapping 10.224.0.34 to 162.159.133.232
antizapret-1         | Feb 08 09:41:58 dnsmap[142]: Reply: [127.0.0.1:45632] (udp) / 'media.discordapp.net.' (A) / RRs: A,A,A,A,A
antizapret-1         | Feb 08 09:41:59 dnsmap[142]: Request: [127.0.0.1:56702] (udp) / 'warsaw10065.discord.media.' (A)
antizapret-1         | Feb 08 09:41:59 dnsmap[142]: GOT A
antizapret-1         | Feb 08 09:41:59 dnsmap[142]: Mapping 10.224.0.35 to 162.159.128.235
antizapret-1         | Feb 08 09:41:59 dnsmap[142]: Mapping 10.224.0.36 to 162.159.130.235
antizapret-1         | Feb 08 09:41:59 dnsmap[142]: Mapping 10.224.0.37 to 162.159.137.234
antizapret-1         | Feb 08 09:41:59 dnsmap[142]: Mapping 10.224.0.38 to 162.159.129.235Request: [127.0.0.1:48101] (udp) / 'warsaw10065.discord.media.' (HTTPS)
antizapret-1         | Feb 08 09:41:59 dnsmap[142]: Mapping 10.224.0.39 to 162.159.138.234
antizapret-1         | Feb 08 09:41:59 dnsmap[142]: Reply: [127.0.0.1:56702] (udp) / 'warsaw10065.discord.media.' (A) / RRs: A,A,A,A,A
antizapret-1         | Feb 08 09:41:59 dnsmap[142]: GOT AAAA or HTTPS
antizapret-1         | Feb 08 09:41:59 dnsmap[142]: Reply: [127.0.0.1:48101] (udp) / 'warsaw10065.discord.media.' (HTTPS) / RRs:
openvpn-1            |
openvpn-1            | ==> /etc/openvpn/log/openvpn-status.log <==
openvpn-1            | n Name,Real Address,Last Ref,Last Ref (time_t)
openvpn-1            | ROUTING_TABLE,10.1.165.2,Keenetic,176.195.230.180:59710,2025-02-08 09:41:33,1739007693
openvpn-1            | GLOBAL_STATS,Max bcast/mcast queue length,0
openvpn-1            | GLOBAL_STATS,dco_enabled,1
openvpn-1            | END
```

Т.е. в контейнерах видна активность, но соединение почему-то не происходит.

В конфиге так же присутствует Wireguard. Если подключаться по нему, то Discord работает отлично. Но пользоваться им не хочется, а хочется сидеть из-за VPN-а, который в роутере. Easy-wg генерирует такой конфиг:

<details>
  <summary>example.conf</summary>

```conf
[Interface]
PrivateKey = secret
Address = 10.1.166.4/24
DNS = 10.224.0.1

[Peer]
PublicKey = secret
PresharedKey = secret
AllowedIPs = 10.1.166.0/24, 10.224.0.0/15, 103.246.200.0/22, 104.109.143.0/24, 178.239.88.0/21, 185.104.45.0/24, 193.105.213.36/30, 203.104.128.0/20, 203.104.144.0/21, 203.104.152.0/22, 34.0.192.0/18, 35.192.0.0/11, 66.22.192.0/18, 68.171.224.0/19, 74.82.64.0/19
Endpoint = secret
PersistentKeepalive = 25

```

</details>

Так же, пробовал сменить протокол OpenVPN на TCP (т.к. на 3 версии, вроде, был именно tcp) - эффекта никакого
