### ISSUE TITLE
Amnezia постоянно падает

### ISSUE THREAD

**Issue by Gruven** [xtrime-ru/antizapret-vpn-docker#146]
Обновился, пересобрал образ, а amnezia теперь падает постоянно. Есть идеи?

```
wireguard-amnezia-1  | 2025-02-11T12:41:28.351969407Z SIGINT signal received.
antizapret-1         | 2025-02-11T12:41:33.766155536Z Feb 11 14:41:33 kernel: br-3bf197a56c72: port 2(veth1ba02eb) entered disabled state
antizapret-1         | 2025-02-11T12:41:33.766171122Z Feb 11 14:41:33 kernel: veth8ed09c1: renamed from eth0
antizapret-1         | 2025-02-11T12:41:33.766175560Z Feb 11 14:41:33 kernel: br-3bf197a56c72: port 2(veth1ba02eb) entered disabled state
antizapret-1         | 2025-02-11T12:41:33.766179703Z Feb 11 14:41:33 kernel: veth1ba02eb (unregistering): left allmulticast mode
antizapret-1         | 2025-02-11T12:41:33.766183484Z Feb 11 14:41:33 kernel: veth1ba02eb (unregistering): left promiscuous mode
antizapret-1         | 2025-02-11T12:41:33.766187403Z Feb 11 14:41:33 kernel: br-3bf197a56c72: port 2(veth1ba02eb) entered disabled state
antizapret-1         | 2025-02-11T12:41:33.766191162Z Feb 11 14:41:33 kernel: br-3bf197a56c72: port 2(veth2d0eea2) entered blocking state
antizapret-1         | 2025-02-11T12:41:33.766195069Z Feb 11 14:41:33 kernel: br-3bf197a56c72: port 2(veth2d0eea2) entered disabled state
antizapret-1         | 2025-02-11T12:41:33.766200143Z Feb 11 14:41:33 kernel: veth2d0eea2: entered allmulticast mode
antizapret-1         | 2025-02-11T12:41:33.766205716Z Feb 11 14:41:33 kernel: veth2d0eea2: entered promiscuous mode
antizapret-1         | 2025-02-11T12:41:33.766211097Z Feb 11 14:41:33 kernel: eth0: renamed from veth7ed8473
wireguard-amnezia-1 exited with code 0
wireguard-amnezia-1  | 2025-02-11T12:41:33.832312532Z   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
wireguard-amnezia-1  | 2025-02-11T12:41:33.832500106Z                                  Dload  Upload   Total   Spent    Left  Speed
100    16  100    16    0     0   1396      0 --:--:-- --:--:-- --:--:--  1454
antizapret-1         | 2025-02-11T12:41:34.066164555Z Feb 11 14:41:33 kernel: br-3bf197a56c72: port 2(veth2d0eea2) entered blocking state
antizapret-1         | 2025-02-11T12:41:34.066185912Z Feb 11 14:41:33 kernel: br-3bf197a56c72: port 2(veth2d0eea2) entered forwarding state
wireguard-amnezia-1  | 2025-02-11T12:41:34.717081100Z 2025-02-11T12:41:34.716Z Server Listening on http://0.0.0.0:6843
wireguard-amnezia-1  | 2025-02-11T12:41:34.720369291Z 2025-02-11T12:41:34.720Z WireGuard Loading configuration...
wireguard-amnezia-1  | 2025-02-11T12:41:34.724374791Z 2025-02-11T12:41:34.724Z WireGuard Configuration loaded.
wireguard-amnezia-1  | 2025-02-11T12:41:34.725042840Z 2025-02-11T12:41:34.724Z WireGuard Config saving...
wireguard-amnezia-1  | 2025-02-11T12:41:34.726796140Z 2025-02-11T12:41:34.726Z WireGuard Config saved.
wireguard-amnezia-1  | 2025-02-11T12:41:34.727903297Z $ wg-quick down wg0
wireguard-amnezia-1  | 2025-02-11T12:41:34.798851485Z $ wg-quick up wg0
wireguard-amnezia-1  | 2025-02-11T12:41:34.910486322Z 2025-02-11T12:41:34.910Z WireGuard Config syncing...
wireguard-amnezia-1  | 2025-02-11T12:41:34.911074724Z $ wg syncconf wg0 <(wg-quick strip wg0)
wireguard-amnezia-1  | 2025-02-11T12:41:34.973991372Z 2025-02-11T12:41:34.973Z WireGuard Config synced.
antizapret-1         | 2025-02-11T12:41:52.066253433Z Feb 11 14:41:51 dnsmap[144]: Request: [127.0.0.1:59644] (udp) / 'www.jetbrains.com.' (A)
antizapret-1         | 2025-02-11T12:41:52.066290914Z Feb 11 14:41:51 dnsmap[144]: GOT A
antizapret-1         | 2025-02-11T12:41:52.066296402Z Feb 11 14:41:51 dnsmap[144]: Mapping 10.224.0.9 to 18.66.102.75
antizapret-1         | 2025-02-11T12:41:52.066300545Z Feb 11 14:41:51 dnsmap[144]: Mapping 10.224.0.10 to 18.66.102.125
antizapret-1         | 2025-02-11T12:41:52.066304437Z Feb 11 14:41:51 dnsmap[144]: Mapping 10.224.0.11 to 18.66.102.54
antizapret-1         | 2025-02-11T12:41:52.066308313Z Feb 11 14:41:51 dnsmap[144]: Mapping 10.224.0.12 to 18.66.102.36
antizapret-1         | 2025-02-11T12:41:52.066312253Z Feb 11 14:41:51 dnsmap[144]: Reply: [127.0.0.1:59644] (udp) / 'www.jetbrains.com.' (A) / RRs: A,A,A,A
wireguard-amnezia-1  | 2025-02-11T12:42:33.871168353Z SIGINT signal received.
antizapret-1         | 2025-02-11T12:42:39.306183357Z Feb 11 14:42:39 kernel: br-3bf197a56c72: port 2(veth2d0eea2) entered disabled state
antizapret-1         | 2025-02-11T12:42:39.306234194Z Feb 11 14:42:39 kernel: veth7ed8473: renamed from eth0
antizapret-1         | 2025-02-11T12:42:39.306239107Z Feb 11 14:42:39 kernel: br-3bf197a56c72: port 2(veth2d0eea2) entered disabled state
antizapret-1         | 2025-02-11T12:42:39.306243044Z Feb 11 14:42:39 kernel: veth2d0eea2 (unregistering): left allmulticast mode
antizapret-1         | 2025-02-11T12:42:39.306247056Z Feb 11 14:42:39 kernel: veth2d0eea2 (unregistering): left promiscuous mode
antizapret-1         | 2025-02-11T12:42:39.306262886Z Feb 11 14:42:39 kernel: br-3bf197a56c72: port 2(veth2d0eea2) entered disabled state
antizapret-1         | 2025-02-11T12:42:39.306266299Z Feb 11 14:42:39 kernel: br-3bf197a56c72: port 2(vethda91b36) entered blocking state
antizapret-1         | 2025-02-11T12:42:39.306269154Z Feb 11 14:42:39 kernel: br-3bf197a56c72: port 2(vethda91b36) entered disabled state
antizapret-1         | 2025-02-11T12:42:39.306272027Z Feb 11 14:42:39 kernel: vethda91b36: entered allmulticast mode
antizapret-1         | 2025-02-11T12:42:39.306274943Z Feb 11 14:42:39 kernel: vethda91b36: entered promiscuous mode
antizapret-1         | 2025-02-11T12:42:39.306277725Z Feb 11 14:42:39 kernel: eth0: renamed from vethaec91a7
wireguard-amnezia-1 exited with code 0
wireguard-amnezia-1  | 2025-02-11T12:42:39.372997312Z   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
wireguard-amnezia-1  | 2025-02-11T12:42:39.374275261Z                                  Dload  Upload   Total   Spent    Left  Speed
100    16  100    16    0     0   1831      0 --:--:-- --:--:-- --:--:--  2000
antizapret-1         | 2025-02-11T12:42:39.566354087Z Feb 11 14:42:39 kernel: br-3bf197a56c72: port 2(vethda91b36) entered blocking state
antizapret-1         | 2025-02-11T12:42:39.566385874Z Feb 11 14:42:39 kernel: br-3bf197a56c72: port 2(vethda91b36) entered forwarding state
wireguard-amnezia-1  | 2025-02-11T12:42:40.288580987Z 2025-02-11T12:42:40.287Z Server Listening on http://0.0.0.0:6843
wireguard-amnezia-1  | 2025-02-11T12:42:40.292438432Z 2025-02-11T12:42:40.292Z WireGuard Loading configuration...
wireguard-amnezia-1  | 2025-02-11T12:42:40.294928027Z 2025-02-11T12:42:40.294Z WireGuard Configuration loaded.
wireguard-amnezia-1  | 2025-02-11T12:42:40.295689989Z 2025-02-11T12:42:40.295Z WireGuard Config saving...
wireguard-amnezia-1  | 2025-02-11T12:42:40.297690955Z 2025-02-11T12:42:40.297Z WireGuard Config saved.
wireguard-amnezia-1  | 2025-02-11T12:42:40.299253991Z $ wg-quick down wg0
wireguard-amnezia-1  | 2025-02-11T12:42:40.375184103Z $ wg-quick up wg0
wireguard-amnezia-1  | 2025-02-11T12:42:40.499274759Z 2025-02-11T12:42:40.499Z WireGuard Config syncing...
wireguard-amnezia-1  | 2025-02-11T12:42:40.499980213Z $ wg syncconf wg0 <(wg-quick strip wg0)
wireguard-amnezia-1  | 2025-02-11T12:42:40.571267789Z 2025-02-11T12:42:40.571Z WireGuard Config synced.
```

**Comment by Gruven** [comment]
Откатился на [старый коммит](https://github.com/xtrime-ru/antizapret-vpn-docker/commit/7150f2d6f15a6ca74cf3944abc22e3b1d1e31e47) - вроде не падает

**Comment by xtrime-ru** [comment]
Нужен полный лог контейнера antizapret. 

В логах видно, что котнейнер amnezia завершается штантно, из за того что получил сигнал SIGINT. Скорее всего это healthcheck из за изменения файла `./config/antizapret/result/blocked-ranges-with-include.txt` , который используется для заполнения списка AllowedIPs

Файл меняется при обновлении списков антизапрета.

**Comment by Ernieleo** [comment]
@xtrime-ru Дополняю описание проблемы и прошу разобраться с ней.

Падение происходит без участия пользователя – достаточно поднять контейнер и просто подождать несколько минут, после чего происходит сбой.

В моём случае я создавал клиентов в WEB-интерфейсе, затем удалил одного из них и больше не выполнял никаких действий, однако спустя некоторое время столкнулся с ошибкой и последующим перезапуском awg. Пытался выявить ошибку, и паттерн возникновения, зависимости не обнаружил, предполагаю косяк в изменениях в релизе. 

Прикладываю лог-файл и пример используемого override:

📎[override-example.txt](https://github.com/user-attachments/files/18759821/override-example.txt)

📎[log.txt](https://github.com/user-attachments/files/18759809/log.txt)

**Comment by Gruven** [comment]
> Можете предоставить свой конфиг docker-compose.override.yml

Да, вот

```yml
services:
  antizapret:
    environment:
      - ADGUARDHOME_PORT=6845
      - ADGUARDHOME_USERNAME=user
      - ADGUARDHOME_PASSWORD=pass
    ports:
      - 6845:6845/tcp
  wireguard-amnezia:
    environment:
      # Разрешить маршрутизацию всех IP адресов, в маршрутизатор в любом случае в ручном режиме добавляются маршруты
      # Таким образом можно использовать подключение для полноценного VPN
      #- WG_ALLOWED_IPS=0.0.0.0/0
      - WG_ALLOWED_IPS=10.224.0.0/15, 10.1.166.0/24, 103.246.200.0/22, 178.239.88.0/21, 185.104.45.0/24, 193.105.213.36/30, 203.104.128.0/20, 203.104.144.0/21, 203.104.152.0/22, 68.171.224.0/19, 74.82.64.0/19, 104.109.143.0/24
      # Принудительное перенаправление всех DNS (udp 53) на antizapret
      # В keenetic прописываем маршрут 77.88.8.8 (или любой друго DNS) на шлюз WG (добавление автоматичеки)
      # При падении WG, DNS работают напрямую
      - FORCE_FORWARD_DNS=true
      # Язык
      - LANG=ru
      # Порт для панели управления WireGuard
      - PORT=6843
      # Порт WireGuard
      - WG_PORT=443
      - WIREGUARD_PASSWORD=pass
    ports:
      # Порт WireGuard
      - "443:443/udp"
      # Порт для панели управления WireGuard
      - "6843:6843/tcp"
    extends:
      file: docker-compose.wireguard-amnezia.yml
      service: wireguard-amnezia
```

Пока нет времени обновиться и забрать полные логи, поэтому не писал.
