### ISSUE TITLE
Доступ к web-панелям только через VPN

### ISSUE THREAD

**Issue by Nuck-TH** [xtrime-ru/antizapret-vpn-docker#168]
Возможно ли так настроить контейнеры? Как-то не очень охота чтобы они торчали в интернет защищённые только паролями...

**Comment by xtrime-ru** [comment]
Уже реализовано. Все контейнеры доступны по урлам в доменной зоне .antizapret: https://github.com/xtrime-ru/antizapret-vpn-docker?tab=readme-ov-file#access-containers-from-local-network

Что бы закрыть наружу порты в контейнерах используйте `!override` и `!reset []` в своем docker-compose.override.yml. Пример: 

```yml
services:
  antizapret:
    environment:
      - ADGUARDHOME_USERNAME=admin
      - ADGUARDHOME_PASSWORD=password
    ports: !reset []

  wireguard-amnezia:
    extends:
      file: services/wireguard/docker-compose.yml
      service: wireguard-amnezia
    ports: !override
      - 51830:51820/udp
    environment:
      - WIREGUARD_PASSWORD=password
      - PORT=51821
      - WG_PORT=51820
      - WG_CONFIG_PORT=51830

  openvpn:
    extends:
      file: services/openvpn/docker-compose.yml
      service: openvpn
    depends_on:
      - openvpn-ui
    ports: !reset []

  openvpn-ui:
    extends:
      file: services/openvpn/docker-compose.yml
      service: openvpn-ui
    environment:
      - OPENVPN_ADMIN_PASSWORD=password
```
