### ISSUE TITLE
Невозможно войти в OpenVPN UI

### ISSUE THREAD

**Issue by Nuck-TH** [xtrime-ru/antizapret-vpn-docker#170]
В другие вебморды входит, в OpenVPN - нет, без выдачи каких-либо ошибок. Доступ через HTTPS.
Пробовал:
- Пароль 25 символов
- Пароль 25 символов без спецсимволов(т.е. только буквы/цифры)
- Пароль 16 символов без спецсимволов
- Браузеры Pale Moon и Edge

Секции относящиеся к OpenVPN:

```
openvpn:
    extends:
      file: services/openvpn/docker-compose.yml
      service: openvpn
    depends_on:
      - openvpn-ui
    ports:
      - <порт>:1194/tcp
      - <порт>:1194/udp

  openvpn-ui:
    extends:
      file: services/openvpn/docker-compose.yml
      service: openvpn-ui
    environment:
      - OPENVPN_ADMIN_PASSWORD=<пароль>
      - OPENVPN_PORT=<порт>
    ports: !reset []
```

Ещё: можно ли сделать генерацию одного файла ovpn автоматически, чтобы можно было подключиться к серверу и работать с вебмордами через тоннель без необходимости выпячивать их в интернет? Сейчас это невозможно, т.к. порты мложно закрыть, а способа сгенерировать файлы для OpenVPN без входа в вебморду нет.
