### ISSUE TITLE
Error starting userland proxy: listen tcp4 0.0.0.0:51821: bind: address already in use

### ISSUE THREAD

**Issue by art3mHQ** [xtrime-ru/antizapret-vpn-docker#61]
Have an issue during Installation, OS: Ubuntu 24.04.1 LTS x86_64 
 
```
root@localhost:~# git clone https://github.com/xtrime-ru/antizapret-vpn-docker.git antizapret
cd antizapret
docker compose pull
docker compose up -d
Cloning into 'antizapret'...
remote: Enumerating objects: 831, done.
remote: Counting objects: 100% (261/261), done.
remote: Compressing objects: 100% (150/150), done.
remote: Total 831 (delta 159), reused 132 (delta 108), pack-reused 570 (from 1)
Receiving objects: 100% (831/831), 124.66 KiB | 5.94 MiB/s, done.
Resolving deltas: 100% (397/397), done.
[+] Pulling 10/10
 ✔ antizapret-vpn Pulled                                                                                                                     16.9s 
   ✔ 31e907dcc94a Pull complete                                                                                                               4.8s 
   ✔ 4f4fb700ef54 Pull complete                                                                                                               4.9s 
   ✔ 0cd6eb3d4c04 Pull complete                                                                                                              11.1s 
   ✔ 2411482dcdae Pull complete                                                                                                              11.2s 
   ✔ 57a90069f3bd Pull complete                                                                                                              11.7s 
   ✔ e4954cfa34c7 Pull complete                                                                                                              11.8s 
   ✔ c0770b612fb4 Pull complete                                                                                                              11.9s 
   ✔ a8f3f258e96c Pull complete                                                                                                              11.9s 
   ✔ d47d640266f9 Pull complete                                                                                                              15.0s 
[+] Running 2/2
 ✔ Network antizapret_default  Created                                                                                                        0.2s 
 ✔ Container antizapret-vpn    Started                                                                                                        2.3s 
root@localhost:~/antizapret# docker run --rm ghcr.io/wg-easy/wg-easy wgpw gasP#-Ri!0CrlDrO$Om! | sed "s/'//g" | sed -r 's/\$/\$\$/g' | tee ./wireguard/wireguard.env
Unable to find image 'ghcr.io/wg-easy/wg-easy:latest' locally
latest: Pulling from wg-easy/wg-easy
c6a83fedfae6: Pull complete 
731f5f878c76: Pull complete 
17ea4cb95273: Pull complete 
2ba186860f73: Pull complete 
258f39275178: Pull complete 
3700239fd420: Pull complete 
360ff0804f5e: Pull complete 
4f4fb700ef54: Pull complete 
856d3d0ce412: Pull complete 
b6e71ca6d913: Pull complete 
Digest: sha256:66352ccb4b5095992550aa567df5118a5152b6ed31be34b0a8e118a3c3a35bf5
Status: Downloaded newer image for ghcr.io/wg-easy/wg-easy:latest
PASSWORD_HASH=$$2a$$12$$U5EHsOhf2sLRFXrb22WAVeeAT6RoYZ1oCt3zIqWvnqebLzfqmwWWK
root@localhost:~/antizapret# ls
Dockerfile  README.md  docker-build.sh             docker-compose.ipsec.yml     docker-compose.wireguard.yml  docs   keys    wireguard
LICENSE.md  config     docker-compose.adguard.yml  docker-compose.override.yml  docker-compose.yml            ipsec  rootfs
root@localhost:~/antizapret# vim docker-compose.wireguard.yml 
root@localhost:~/antizapret# docker compose -f docker-compose.wireguard.yml pull
docker compose -f docker-compose.wireguard.yml up -d
[+] Pulling 2/2
 ✔ wg-easy Pulled                                                                                                                             0.5s 
 ✔ antizapret-vpn Pulled                                                                                                                      1.0s 
[+] Running 1/2
 ✔ Container antizapret-vpn  Running                                                                                                          0.0s 
 ⠸ Container wg-easy         Starting                                                                                                         0.4s 
Error response from daemon: driver failed programming external connectivity on endpoint wg-easy (d200c839bc64326ca8ae0f4c19b1f6a5a35c26f423f1a983d81ada5251c465e2): failed to bind port 0.0.0.0:51821/tcp: Error starting userland proxy: listen tcp4 0.0.0.0:51821: bind: address already in use
```

is it possible to have both openvpn and wireguard clients? Thank you

**Comment by art3mHQ** [comment]
> seems like port is already used by another process

nothing else except antizapret is runnig

**Comment by Dimariqe** [comment]
> > seems like port is already used by another process
> 
> nothing else except antizapret is runnig

Show your `docker-compose.wireguard.yml`

**Comment by art3mHQ** [comment]
> Show your `docker-compose.wireguard.yml`

```
services:
  antizapret-vpn:
    extends:
      file: docker-compose.yml
      service: antizapret-vpn
  wg-easy:
    environment:
      - WG_ALLOWED_IPS=
          10.0.0.0/8,
          103.246.200.0/22,
          178.239.88.0/21,
          185.104.45.0/24,
          193.105.213.36/30,
          203.104.128.0/20,
          203.104.144.0/21,
          203.104.152.0/22,
          68.171.224.0/19,
          74.82.64.0/19,
          104.109.143.0/24
      - WG_DEFAULT_DNS=10.0.0.1
      - WG_PERSISTENT_KEEPALIVE=25
      - WG_PORT=443
    image: ghcr.io/wg-easy/wg-easy
    container_name: wg-easy
    volumes:
      - ./.etc_wireguard:/etc/wireguard
      - ./wireguard/entrypoint.sh:/entrypoint.sh
    env_file:
      - ./wireguard/wireguard.env
    command: /entrypoint.sh
    ports:
      - "443:443/udp"
      - "51821:51821/tcp"
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    depends_on:
      - antizapret-vpn
    sysctls:
      - net.ipv4.ip_forward=1
      - net.ipv4.conf.all.src_valid_mark=1
    logging:
      driver: "json-file"
      options:
        max-size: "100k"
        max-file: "2"root@localhost:~/antizapret# 

```

i think i did not change nothing

**Comment by Dimariqe** [comment]
Change the Web panel port:
```yaml
services:
  antizapret-vpn:
    extends:
      file: docker-compose.yml
      service: antizapret-vpn
  wg-easy:
    environment:
      - WG_ALLOWED_IPS=
          10.0.0.0/8,
          103.246.200.0/22,
          178.239.88.0/21,
          185.104.45.0/24,
          193.105.213.36/30,
          203.104.128.0/20,
          203.104.144.0/21,
          203.104.152.0/22,
          68.171.224.0/19,
          74.82.64.0/19,
          104.109.143.0/24
      - WG_DEFAULT_DNS=10.0.0.1
      - WG_PERSISTENT_KEEPALIVE=25
      - WG_PORT=443
      - PORT=51811
    image: ghcr.io/wg-easy/wg-easy
    container_name: wg-easy
    volumes:
      - ./.etc_wireguard:/etc/wireguard
      - ./wireguard/entrypoint.sh:/entrypoint.sh
    env_file:
      - ./wireguard/wireguard.env
    command: /entrypoint.sh
    ports:
      - "443:443/udp"
      - "51811:51811/tcp"
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    depends_on:
      - antizapret-vpn
    sysctls:
      - net.ipv4.ip_forward=1
      - net.ipv4.conf.all.src_valid_mark=1
    logging:
      driver: "json-file"
      options:
        max-size: "100k"
        max-file: "2"
``` 
I also recommend looking at what is occupying port `51821`:
`netstat -ltnp | grep -w 51821`
