### ISSUE TITLE
No way to override WG_HOST

### ISSUE THREAD

**Issue by BATCOH** [xtrime-ru/antizapret-vpn-docker#94]
docker-compose.override.yml
```yml
services:
  antizapret-vpn:
    environment:
      - SKIP_UPDATE_FROM_ZAPRET=true
  amnezia-wg-easy:
    extends:
      file: docker-compose.wireguard-amnezia.yml
      service: amnezia-wg-easy
    environment:
      - WG_HOST=vpn.example.com
```
wireguard client config file:
```
...
Endpoint = 93.184.215.14:443
...
```
